<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyOriginatorKeyFile>..\..\key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Records\NumberChart.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\b2xtranslator.csproj" />
  </ItemGroup>
</Project>